/**
 * Awards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IUserDto } from './user-dto';

/**
 * Элемент списка комментариев
 */
export interface ICommentsItemDto {
	/**
	 * Айди комментария
	 */
	id?: number;
	user?: IUserDto;
	/**
	 * Дота комментария
	 */
	createdDate?: string;
	/**
	 * Комментарий
	 */
	note?: string | null;
}
