/**
 * Awards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IObjectType } from './object-type';

/**
 * Модель для комментария
 */
export interface ICommentRequest {
	/**
	 * Айди объекта
	 */
	objectId?: number;
	type?: IObjectType;
	/**
	 * Айди награды доступно только для Ген Директора
	 */
	awardId?: number | null;
	/**
	 * Комментарий
	 */
	note?: string | null;
}
export namespace ICommentRequest {}
