/**
 * Awards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Модель дистрибьютора
 */
export interface IDistributorDto { 
    /**
     * Айди дистрибьютора
     */
    id?: number;
    /**
     * Название
     */
    name?: string | null;
    /**
     * Картинка
     */
    avatarUrl?: string | null;
}

