/**
 * Awards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IPartnerThanksItemDto } from './partner-thanks-item-dto';

/**
 * Модель виджета \"Спасибо партнерам\"
 */
export interface IPartnerThanksListDto {
	/**
	 * Ссылка на сказать спасибо партнерам
	 */
	addNewThanksLink?: string | null;
	/**
	 * За все время
	 */
	totalCount?: number;
	/**
	 * Всего за неделю
	 */
	weekCount?: number;
	/**
	 * Список лидеров на указанную дату
	 */
	items?: IPartnerThanksItemDto[] | null;
}
