/**
 * Awards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IUserDto } from '@app/core/models/awards/user-dto';

/**
 * Айтем лидера
 */
export interface IPartnerThanksItemDto {
	/**
	 * Айди пользователя
	 */
	id?: number;
	/**
	 * Ссылка на аватарку пользователя
	 */
	user: IUserDto;
	/**
	 * Количество спасибо партнеру
	 */
	thanksCount?: number;
	/**
	 * Место в рейтинге
	 */
	place?: IPartnerPlaceEmblem;
}

export enum IPartnerPlaceEmblem {
	gold = 1,
	silver = 2,
	cooper = 3,
}
