/**
 * Awards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IProjectDto } from './project-dto';
import { IDistributorDto } from './distributor-dto';
import { ITeamDto } from './team-dto';
import { IUserDto } from './user-dto';
import { RateTypeEnum } from './rate-type';
import {TypeCup} from "@app/widgets/rating/rating-team-tab/rating-team-tab.component";

/**
 * Элемент списка рейтинга
 */
export interface IRankItemDto {
	user: IUserDto;
	project?: IProjectDto;
	distributor?: IDistributorDto;
	team: ITeamDto;
	teamName: string;

	/**
	 * Место
	 */
	place: TypeCup;
	/**
	 * Средний рейтинг за неделю
	 */
	avgWeekRate?: number | null;
	/**
	 * Квартальный средний рейтинг
	 */
	avgQuarterRate?: number | null;
	type: RateTypeEnum;
	/**
	 * Ссылка на детали объекта
	 */
	detailLink?: string | null;
	/**
	 * Ссылка для переписки если доступна текущему пользователю (null в противном случае)
	 */
	talksLink?: string | null;
	/**
	 * Количество сообщений в переписке
	 */
	msgCount?: number;
	/**
	 * Отображение иконки переписки
	 */
	allowMsgView?: boolean;
}
export namespace IRankItemDto {}
