/**
 * Awards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Тип рейтинга
 */
export interface IRankTypeItemDto {
	/**
	 * Айди типа рейтинга
	 */
	id: number;
	/**
	 * Краткое название
	 */
	shortName: string;
	/**
	 * Полное название
	 */
	name: string;
	/**
	 * Рейтинг
	 */
	rate?: number;
	/**
	 * Количество участников в рейтинге
	 */
	membersCount?: number;
	/**
	 * Место
	 */
	place: number;

	selected?: boolean;

	signature: string;

	reportAvailable: true;
}
