/**
 * Awards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IRankTypeItemDto } from './rank-type-item-dto';

/**
 * Список типов рейтингов
 */
export interface IRankTypeListDto {
	/**
	 * Средняя оценка по всем рейтингам
	 */
	averageAll: number;
	/**
	 * Количество участников во всех рейтингах
	 */
	membersTotal: number;
	/**
	 * Выбранный по умолчанию тип рейтинга
	 */
	rankTypeId: number;
	/**
	 * Список элементов
	 */
	items: IRankTypeItemDto[];
}
