/**
 * Awards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *   0 = Mol  1 = Projects  2 = Distributors  3 = Teams
 */
export enum RateTypeEnum {
	Mol = 0,
	Projects = 1,
	Distributors = 2,
	Teams = 3,
}
