/**
 * Awards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *   0 = Mol  1 = Projects  2 = Distributors  3 = Teams
 */
export type IRateType = 0 | 1 | 2 | 3;

export const IRateType = {
	NUMBER_0: 0 as IRateType,
	NUMBER_1: 1 as IRateType,
	NUMBER_2: 2 as IRateType,
	NUMBER_3: 3 as IRateType,
};
