/**
 * Awards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IUserDto } from './user-dto';


/**
 * Модель команды
 */
export interface ITeamDto { 
    /**
     * Айди команды
     */
    id?: number;
    /**
     * Название
     */
    name?: string | null;
    /**
     * Картинка
     */
    avatarUrl?: string | null;
    /**
     * Участники команды
     */
    members?: Array<IUserDto> | null;
}

