/**
 * Awards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IUserDto } from './user-dto';

/**
 * Элемент списка \"спасибо коллегам\"
 */
export interface IThankItemDto {
	/**
	 * Айди
	 */
	id?: number;
	fromUser?: IUserDto;
	toUser?: IUserDto;
	/**
	 * Текст
	 */
	text?: string | null;
	/**
	 * Дата создания
	 */
	createdDate?: string;
	/**
	 * Количество лайков
	 */
	likesCount?: number;
	/**
	 * Медаль и ее место если есть
	 */
	award?: number | null;
	/**
	 * Количество комментариев
	 */
	commentsCount?: number;
	/**
	 * Флаг что пользователь уже лайкнул
	 */
	isUserLiked?: boolean;
}
