/**
 * Awards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Сказать спасибо коллеге
 */
export interface IThanksRequest {
	/**
	 * Коллега которому говоорим спасибо
	 */
	userId?: number;
	/**
	 * Сообщение
	 */
	note?: string | null;
}
