/**
 * Awards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Модель пользователя
 */
export interface IUserDto { 
    /**
     * Айди пользователя
     */
    id?: number;
    /**
     * Ссылка на аватарку пользователя
     */
    avatarUrl?: string | null;
    /**
     * ФИО
     */
    name?: string | null;
    /**
     * Фамилия
     */
    lastName?: string | null;
    /**
     * Имя
     */
    firstName?: string | null;
    /**
     * Отчество
     */
    surName?: string | null;
    /**
     * Подразделение
     */
    department?: string | null;
    /**
     * Должность
     */
    position?: string | null;
    /**
     * На испытательном сроке
     */
    onProbation?: boolean;
}

