/**
 * Awards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Модель создания победы
 */
export interface IWinRequest {
	/**
	 * Текст победы
	 */
	text?: string | null;
	/**
	 * Список айди пользователей для совместной Победы
	 */
	userIds?: number[] | null;
	/**
	 * Список айди связанных продуктов
	 */
	productIds?: number[] | null;
}
