/**
 * Awards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LikeStateEnum } from '@app/shared/components/like/like.component';
import { IUserDto } from './user-dto';

/**
 * Модель элемента списка
 */
export interface IWinsItemDto {
	/**
	 * Айди задачи
	 */
	id: number;
	user?: IUserDto;
	/**
	 * Описание достижения
	 */
	note?: string | null;
	/**
	 * Дата достижения
	 */
	createdDate?: string;
	/**
	 * Количество лайков
	 */
	likesCount?: number;
	/**
	 * Медаль и ее место если есть
	 */
	award?: LikeStateEnum;
	/**
	 * Количество комментариев
	 */
	commentsCount?: number;
	/**
	 * Список других участников для групповой победы
	 */
	groupWinUsers: IUserDto[] | null;
	/**
	 * Флаг что пользователь уже лайкнул
	 */
	isUserLiked?: boolean;
	/**
	 * Ссылка на детали победы
	 */
	detailUrl?: string | null;

	likedUsers: IUserDto[] | null;
}
