/**
 * Awards API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IWinsItemDto } from './wins-item-dto';


/**
 * Модель списка виджета победы
 */
export interface IWinsListDto { 
    items?: Array<IWinsItemDto> | null;
    total?: number;
    /**
     * Расширенный режим для Ген Дира
     */
    isExtendedMode?: boolean;
    /**
     * Ссылка на список активностей
     */
    linkToActivity?: string | null;
}

