/**
 * Sales API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IProficitDto } from './proficit-dto';


/**
 * Обертка для аукционных продаж
 */
export interface IAuctionSalesDto { 
    /**
     * Ссылка на список всех в старой системе
     */
    allListLink?: string | null;
    /**
     * Список аукционных продаж
     */
    items?: Array<IProficitDto> | null;
    /**
     * Всего записей по запросу
     */
    total?: number;
}

