/**
 * Sales API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Аукционная продажа
 */
export interface IProficitDto { 
    /**
     * Ссылка на детали в старой системе
     */
    detailUrl?: string | null;
    /**
     * Айди продажи
     */
    id?: number;
    /**
     * Название товара
     */
    tovName?: string | null;
    /**
     * Единица измерения
     */
    tovUnitName?: string | null;
    /**
     * Цена
     */
    price?: number;
    /**
     * Валюта
     */
    currency?: string | null;
    /**
     * Доступность
     */
    source?: string | null;
    /**
     * Количество
     */
    quantity?: number;
}

