import { TableColumnConfig } from '@front-library/components/lib/components/table/models';

export const columnOperationPlanConfigs: TableColumnConfig[] = [
	{
		id: 'tov',
		name: 'Готовая продукция (ГП)',
		showInDropdown: false,
		showInHeader: true,
		visible: true,
		stickyColumn: true,
	},
	{
		id: 'tovCategory',
		name: 'Категория',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'productionSection',
		name: 'Участок',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'optimalBatch',
		name: 'Оптимальная партия, КГ',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'productionType',
		name: 'Тип продукции',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'productionCity',
		name: 'Город',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'productManagerUser',
		name: 'Менеджер ТМЗ',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'planEconomicUser',
		name: 'Менеджер ПЭО',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'planDays',
		name: 'Неделя',
		showInDropdown: true,
		showInHeader: false,
		visible: true,
		subGroups: [],
	},
	{
		id: 'week-06-23',
		name: '06-23',
		showInDropdown: false,
		showInHeader: true,
		visible: true,
		subColumns: [],
	},
	{
		id: 'planQuantity-06-23',
		name: 'План',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'factQuantity-06-23',
		name: 'Факт',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'week-06-24',
		name: '06-24',
		showInDropdown: false,
		showInHeader: true,
		visible: true,
		subColumns: ['planQuantity-06-24', 'factQuantity-06-24'],
	},
	{
		id: 'planQuantity-06-24',
		name: 'План',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'factQuantity-06-24',
		name: 'Факт',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'week-06-25',
		name: '06-25',
		showInDropdown: false,
		showInHeader: true,
		visible: true,
		subColumns: ['planQuantity-06-25', 'factQuantity-06-25'],
	},
	{
		id: 'planQuantity-06-25',
		name: 'План',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'factQuantity-06-25',
		name: 'Факт',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'week-06-26',
		name: '06-26',
		showInDropdown: false,
		showInHeader: true,
		visible: true,
		subColumns: ['planQuantity-06-26', 'factQuantity-06-26'],
	},
	{
		id: 'planQuantity-06-26',
		name: 'План',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'factQuantity-06-26',
		name: 'Факт',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'week-06-27',
		name: '06-27',
		showInDropdown: false,
		showInHeader: true,
		visible: true,
		subColumns: ['planQuantity-06-27', 'factQuantity-06-27'],
	},
	{
		id: 'planQuantity-06-27',
		name: 'План',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'factQuantity-06-27',
		name: 'Факт',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'week-06-28',
		name: '06-28',
		showInDropdown: false,
		showInHeader: true,
		visible: true,
		subColumns: ['planQuantity-06-28', 'factQuantity-06-28'],
	},
	{
		id: 'planQuantity-06-28',
		name: 'План',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'factQuantity-06-28',
		name: 'Факт',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'week-06-29',
		name: '06-29',
		showInDropdown: false,
		showInHeader: true,
		visible: true,
		subColumns: ['planQuantity-06-29', 'factQuantity-06-29'],
	},
	{
		id: 'planQuantity-06-29',
		name: 'План',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'factQuantity-06-29',
		name: 'Факт',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'weekPlanQuantity',
		name: 'План (нед)',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'weekFactQuantity',
		name: 'Факт (нед)',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'monthPlanQuantity',
		name: 'План (мес)',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
	{
		id: 'monthFactQuantity',
		name: 'Факт (мес)',
		showInDropdown: true,
		showInHeader: true,
		visible: true,
	},
];
