export enum SearchTypeEnum {
	User = 'user',
	UserDictionary = 'user-dictionary',
	SubSector = 'subsector',
	Tovs = 'tovs',
	TovsManufacturing = 'tovsManufacturing',
	PersonificationStatuses = 'personificationStatuses',
	Region = 'region',
	Contractor = 'contractor',
	ContractorManufacturing = 'contractorManufacturing',
	Client = 'client',
	Technologist = 'technologist',
	Contract = 'contract',
	Global = 'global',
	Products = 'products',
}
