/**
 * Company API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface IPrice {
	tovId: number;
	price: number;
	name: string;
}

export interface IAdvantage {
	id: number;
	name: string;
}

export interface IFilesProposals {
	id: number;
	type: number;
	name: string;
	url: string;
	checked: boolean;
	uniqId: string;
}

export interface IClientOffersDto {
	productionId: number;
	productionName: string;
	tovGroupId: number;
	tovGroupName: string;
	tovSubGroupId: number;
	tovSubGroupName: string;
	tovProductionId: number;
	newProductName: string;
	saleClientsCount: number;
	salesWeight: number;
	rating: number;
	newProductUrl: string;
	tovGroupUrl: string;
	productionUrl: string;
	productionGroupUrl: string;
	prices: IPrice[];
	advantages: IAdvantage[];
	promotionalMaterials: IFilesProposals[];
	documents: IFilesProposals[];
}

export interface IRequestGetClientOffer {
	clientId: number;
	productionIds: number[];
	TovGroups: number[];
	TprFlags: number[];
	TovSubGroups: number[];
}

export enum ClientProposalsTypeDocuments {
	rim = 0,
	documents,
}
