/**
 * Company API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface IPrice {
	price: number;
	name: string;
}

export interface IAdvantage {
	id: number;
	name: string;
}

export interface IFilesProposals {
	id: number;
	type: number;
	name: string;
	url: string;
	checked: boolean;
}

export interface IClientPropNewProducts {
	tovProductionId: number;
	newProductName: string;
	saleClientsCount: number;
	salesWeight: number;
	rating: number;
	prices: IPrice[];
	advantages: IAdvantage[];
	promotionalMaterials: IFilesProposals[];
	documents: IFilesProposals[];
}

export interface IClientPropProductionGroups {
	productionGroupId: number;
	productionGroupName: string;
	clientPropNewProducts: IClientPropNewProducts[];
}

export interface IClientPropTovGroups {
	tovGroupId: number;
	tovGroupName: string;
	clientPropProductionGroups: IClientPropProductionGroups[];
}

export interface IClientOffersDto {
	productionId: number;
	productionName: string;
	clientPropTovGroups: IClientPropTovGroups[];
}

export interface IRequestGetClientOffer {
	clientId: number;
	productionIds: number[];
}
