/**
 * Company API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IDictionaryItemDto } from '@app/core/models/company/dictionary-item-dto';

/**
 * Модель банера
 */
export interface IDevelopmentDto {
	/**
	 * Идентификатор
	 */
	id: number;
	/**
	 * Название
	 */
	name: string;
	/**
	 * Ссылка на детальную страницу
	 */
	linkToDetail: string;
	/**
	 *  Дата
	 */
	reportDate: string;
	sale: string;
	status: IDictionaryItemDto;
}
