/**
 * Notification API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Модель прикрепленного файла
 */
export interface IAttachmentDto {
	/**
	 * Уникальный идентификатор
	 */
	id?: string;
	/**
	 * Имя файла
	 */
	fileName?: string | null;
	/**
	 * Размер файла
	 */
	size?: number | null;
	/**
	 * ContentType
	 */
	contentType?: string | null;
	/**
	 * Url
	 */
	directUrl?: string | null;
}
