/**
 * Notification API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Тип переписки  0 = Paroles
 */
export type IConversationType = 0;

export const IConversationType = {
	NUMBER_0: 0 as IConversationType,
};
