/**
 * Notification API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IUserDto } from './user-dto';
import { IAttachmentDto } from './attachment-dto';

/**
 * Модель элемента списка сообщения
 */
export interface IMessageItemDto {
	/**
	 * Айди сообщения
	 */
	id?: string | null;
	/**
	 * Тема сообщения
	 */
	subject?: string | null;
	/**
	 * Список айди пользователей, кому отправляем
	 */
	toUsers?: IUserDto[] | null;
	/**
	 * Список айди пользователей, кому отправить копию
	 */
	copyUsers?: IUserDto[] | null;
	/**
	 * Сообщение
	 */
	text?: string | null;
	author?: IUserDto;
	/**
	 * Ответ на сообщение с данным айди
	 */
	replyToMessageId?: string | null;
	replyToMessage?: IMessageItemDto;
	/**
	 * Список прикрепленных файлов
	 */
	attachments?: IAttachmentDto[] | null;
	/**
	 * Дата создания
	 */
	createdAt?: string;
	/**
	 * Признак приватного сообщения
	 */
	isPrivate?: boolean;
}
