/**
 * Notification API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {CorrespondenceTypeEnum} from "@app/widgets/correspondence/correspondence-type-enum";

/**
 * Модель отправки сообщения
 */
export interface ISendMessageRequest {
	/**
	 * Айди оьъекта переписки
	 */
	objectId?: number;
	type?: CorrespondenceTypeEnum;
	/**
	 * Тема сообщения
	 */
	subject?: string | null;
	/**
	 * Сообщение
	 */
	text?: string | null;
	/**
	 * Список айди пользователей, кому отправляем
	 */
	toUserIds?: number[] | null;
	/**
	 * Список айди пользователей, кому отправить копию
	 */
	copyUserIds?: number[] | null;
	/**
	 * Доступно для просмотра только адресатам
	 */
	isPrivate?: boolean;
	/**
	 * Ответ на сообщение с данным айди
	 */
	replyToMessageId?: string | null;
	/**
	 * Список айди присоединяемых файлов
	 */
	fileIds?: string[] | null;

	sourceUrl?: string;
}
export namespace ISendMessageRequest {}
