apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/component: {{ .Values.component }}
    app.kubernetes.io/part-of: {{ .Values.partOf }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "app.name" . }}
      app.kubernetes.io/component: {{ .Values.component }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "app.name" . }}
        app.kubernetes.io/component: {{ .Values.component }}
        app.kubernetes.io/env: {{ .Values.env }}
        app.kubernetes.io/part-of: {{ .Values.partOf }}
      annotations:
        co.elastic.logs/enabled: 'true'
        co.elastic.logs/json.ignore_decoding_error: 'true'
        co.elastic.logs/json.keys_under_root: 'true'
        co.elastic.logs/json.message_key: message
    spec:
      containers:
      - name: {{ include "app.name" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.service.port }}
        {{- if .Values.config.envs }}
        env:
        {{- range $key, $val := .Values.config.envs }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu | toString }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu | toString }}
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: {{ .Values.service.port }}
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        #   timeoutSeconds: 2
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: {{ .Values.service.port }}
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        #   timeoutSeconds: 2