/**
 * Auth API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface IAddressBookItemDto {
	id?: number;
	avatarUrl?: string | null;
	name?: string | null;
	lastName?: string | null;
	firstName?: string | null;
	surName?: string | null;
	email?: string | null;
	department?: string | null;
	position?: string | null;
	phone?: string | null;
	phoneLocal?: string | null;
	linkToCall?: string | null;
	isIntranet?: boolean;
}
