/**
 * Auth API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IFriendAccountDto } from './friend-account-dto';


export interface IUserDetails { 
    id?: number;
    avatarUrl?: string | null;
    name?: string | null;
    lastName?: string | null;
    firstName?: string | null;
    surName?: string | null;
    email?: string | null;
    department?: string | null;
    position?: string | null;
    phone?: string | null;
    birthDate?: string | null;
    phoneLocal?: string | null;
    skype?: string | null;
    loggedUser?: IFriendAccountDto;
    isAdmin?: boolean;
    headName?: string | null;
    chiefName?: string | null;
    linkToCall?: string | null;
    isIntranet?: boolean;
}

