/**
 * Search API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Тип найденного элемента  1 = User  2 = Organization  3 = Product  4 = Tov  5 = Menu  6 = ProductComment
 */
export type IItemType = 1 | 2 | 3 | 4 | 5 | 6;

export const IItemType = {
    NUMBER_1: 1 as IItemType,
    NUMBER_2: 2 as IItemType,
    NUMBER_3: 3 as IItemType,
    NUMBER_4: 4 as IItemType,
    NUMBER_5: 5 as IItemType,
    NUMBER_6: 6 as IItemType
};

