/**
 * Search API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IItemType } from './item-type';

/**
 * Элемент поиска
 */
export interface ISearchItem {
	type?: IItemType;
	/**
	 * Заголовок
	 */
	title?: string | null;
	/**
	 * Телефон если тип элемента пользователь
	 */
	phone?: string | null;
	/**
	 * Текущему пользователю доступен звоной по IP-телефонии
	 */
	viewerIsIpPhone?: boolean | null;
	/**
	 * Ссылка на детальную страницу
	 */
	linkToDetail?: string | null;
	/**
	 * Локальный номер если тип элемента пользователь
	 */
	phoneLocal?: string | null;
	/**
	 * Сылка на звонок Ip-телефонии
	 */
	linkToCall?: string | null;
}
export namespace ISearchItem {}
