/**
 * Company API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Модель банера
 */
export interface IBannerDto {
	/**
	 * Айди банера
	 */
	id?: number;
	/**
	 * Текстовое описание банера
	 */
	text?: string | null;
	/**
	 * Айди файла
	 */
	fileId?: string;
	/**
	 * Ссылка на изображение банера
	 */
	imageUrl?: string | null;
	/**
	 * Ссылка для перехода по клику (опционально)
	 */
	linkUrl?: string | null;
	/**
	 * Порядок банера
	 */
	order?: number;
}
