/**
 * Company API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IDictionaryItemDto } from './dictionary-item-dto';
import { IClientStatus } from './client-status';
import { IContractorItemDto } from './contractor-item-dto';
import { IManagerItemDto } from './manager-item-dto';
import { ISubSectorItemDto } from './sub-sector-item-dto';

/**
 * Модель деталей клиента
 */
export interface IClientDto {
	/**
	 * Айди клиента
	 */
	id?: number;
	/**
	 * Код клиента
	 */
	code?: number;
	/**
	 * Название клиента
	 */
	name?: string | null;
	category?: IDictionaryItemDto;
	/**
	 * Направление продаж
	 */
	saleDirection?: string | null;
	mainSector?: string | null;
	status?: IClientStatus;
	/**
	 * Передано в юр. отдел
	 */
	transferredToLD?: boolean;
	/**
	 * Нет активности по клиенту
	 */
	noActivity?: boolean;
	/**
	 * Подотрасли
	 */
	sectorParts?: ISubSectorItemDto[] | null;
	region?: IDictionaryItemDto;
	/**
	 * Дата добавления в базу МП, если добавлен
	 */
	introducedAtSM?: string | null;
	/**
	 * Это дистрибьютор
	 */
	isDistributor?: boolean;
	/**
	 * Среднемесячный объем продаж за квартал
	 */
	avgSalesVolume?: number | null;
	/**
	 * Эксклюзивный дистрибьютор в регионе
	 */
	exclusiveInRegion?: boolean | null;
	/**
	 * Эксклюзивный дистрибьютор
	 */
	exclusive?: boolean | null;
	/**
	 * Структура соответствует требованиям
	 */
	meetsRequirements?: boolean | null;
	/**
	 * Список контрагентов
	 */
	contractors?: IContractorItemDto[] | null;
	/**
	 * Список менеджеров
	 */
	managers?: IManagerItemDto[] | null;
	changePriceListLevelLink?: string | null;
	linkToDetail?: string | null;
}
export interface IClientDataDto {
	data: IClientDto;
	permissions: string[];
}

export namespace IClientDto {}
