/**
 * Company API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Статус клиента  1 = New  2 = Active  3 = Archive
 */
export type IClientStatus = 1 | 2 | 3;

export const IClientStatus = {
	NUMBER_1: 1 as IClientStatus,
	NUMBER_2: 2 as IClientStatus,
	NUMBER_3: 3 as IClientStatus,
};
