/**
 * Company API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IDictionaryItemDto } from './dictionary-item-dto';

/**
 * Модель элемента списка Клиентов
 */
export interface IClientItemDto {
	/**
	 * Айди клиента
	 */
	id?: number;
	/**
	 * Название клиента
	 */
	name?: string | null;
	/**
	 * Список контрагентов
	 */
	contractors?: IDictionaryItemDto[] | null;
	/**
	 * Список менеджеров
	 */
	managers?: IDictionaryItemDto[] | null;
	/**
	 * Дата добавления в базу МП, если добавлен
	 */
	introducedAtSM?: string | null;
	/**
	 * Направление продаж
	 */
	saleDirection?: string | null;
	category?: IDictionaryItemDto;
	region?: IDictionaryItemDto;
	/**
	 * Дата архивации, если в статусе \"Архивирован\"
	 */
	archiveDate?: string | null;
	status: IDictionaryItemDto;
	isBaseManagerFired: boolean;
}
