/**
 * Company API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IClientStatus } from './client-status';

/**
 * Модель редактирования клиента
 */
export interface IClientEditRequest {
	/**
	 * Название клиента
	 */
	name?: string | null;
	status?: IClientStatus;
	/**
	 * Айди подотраслей
	 */
	subSectorsIds?: number[] | null;
	/**
	 * Айди региона
	 */
	regionId?: number;
}
export namespace IClientEditRequest {}
