/**
 * Company API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ICreditStatus } from './credit-status';
import { IContractorStatus } from './contractor-status';

/**
 * Модель айтема списка контрагентов
 */
export interface IContractorItemDto {
	/**
	 * Код
	 */
	id?: number;
	/**
	 * Название
	 */
	name?: string | null;
	/**
	 * ИНН
	 */
	inn?: string | null;
	status?: IContractorStatus;
	creditStatus?: ICreditStatus;
	/**
	 * Признак удаленного
	 */
	isDeleted?: boolean;
}
export namespace IContractorItemDto {}
