/**
 * Company API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Статус контрагента  0 = Draft  1 = Accepted  5 = Agreement  6 = New  11 = Revision  -1 = Archive
 */
export type IContractorStatus = 0 | 1 | 5 | 6 | 11 | -1;

export const IContractorStatus = {
	NUMBER_0: 0 as IContractorStatus,
	NUMBER_1: 1 as IContractorStatus,
	NUMBER_5: 5 as IContractorStatus,
	NUMBER_6: 6 as IContractorStatus,
	NUMBER_11: 11 as IContractorStatus,
	NUMBER_MINUS_1: -1 as IContractorStatus,
};
