/**
 * Company API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Кредитный статус  6 = Paying  10 = TransferredToLD  11 = TransferredToSKB  15 = LetterOfGuarantee  16 = LegalLetter  17 = Arbitration
 */
export type ICreditStatus = 6 | 10 | 11 | 15 | 16 | 17;

export const ICreditStatus = {
	NUMBER_6: 6 as ICreditStatus,
	NUMBER_10: 10 as ICreditStatus,
	NUMBER_11: 11 as ICreditStatus,
	NUMBER_15: 15 as ICreditStatus,
	NUMBER_16: 16 as ICreditStatus,
	NUMBER_17: 17 as ICreditStatus,
};
