/**
 * Company API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Элемента списка валют
 */
export interface ICurrencyItemDto { 
    /**
     * Название валюты
     */
    currencyName?: string | null;
    /**
     * Курс к рублю на сегодня
     */
    todayRate?: number;
    /**
     * Курс к рублю на вчера
     */
    yesterdayRate?: number;
    /**
     * Курс к рублю на завтра
     */
    tomorrowRate?: number | null;
}

