/**
 * Company API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ICurrencyItemDto } from './currency-item-dto';


/**
 * Список валют
 */
export interface ICurrencyListDto { 
    /**
     * Ссылка на курсы за все дни
     */
    lintToAll?: string | null;
    /**
     * Список валют
     */
    items?: Array<ICurrencyItemDto> | null;
}

