/**
 * Company API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IId } from '@app/pages/production-plan/component-and-service-for-lib/i-id';

/**
 * Модель айтема словаря
 */
export interface IDictionaryItemDto extends IId {
	/**
	 * Название
	 */
	name: string;
	/**
	 * link
	 */
	linkToDetail?: string | null;

	parentId?: number;

	isCurrent?: boolean;
}
