/**
 * Company API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Элемент меню
 */
export interface IFavoriteMenuItemDto {
	/**
	 * Айди меню
	 */
	id?: number;
	/**
	 * Название элемента меню
	 */
	name?: string | null;
	/**
	 * Ссылка для перехода
	 */
	link?: string | null;
}
