/**
 * Company API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BehaviorSubject } from 'rxjs';

/**
 * Элемент меню
 */
export interface IMenuItemDto {
	/**
	 * Айди меню
	 */
	id?: number;
	/**
	 * Название элемента меню
	 */
	name?: string | null;
	/**
	 * Ссылка для перехода
	 */
	link?: string | null;
	/**
	 * Вложенные элементы подменю
	 */
	items?: IMenuItemDto[] | null;
	/**
	 * Вложенные элементы подменю
	 */
	toggle$?: BehaviorSubject<boolean> | null;
}
