/**
 * Company API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Модель маршрута
 */
export interface IRouteDto { 
    /**
     * Айди маршрута
     */
    id?: number;
    /**
     * Начало маршрута
     */
    startRoute?: string | null;
    /**
     * Конец маршрута
     */
    endRoute?: string | null;
    /**
     * Время выезда
     */
    departureTime?: Array<string> | null;
}

