/**
 * Company API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IClientStatus } from './client-status';

/**
 * Фильт поиска по клиентам
 */
export interface ISearchClientParameters {
	limit?: number;
	offset?: number;
	/**
	 * Айди контрагента
	 */
	contactorId?: number | null;
	/**
	 * Айди менеджера
	 */
	managerId?: number | null;
	status?: IClientStatus;
	/**
	 * Без базового менеджера
	 */
	withoutBaseManager?: boolean | null;
}
export namespace ISearchClientParameters {}
