/**
 * Company API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IRouteDto } from './route-dto';
import { ITransportNotifyDto } from './transport-notify-dto';

/**
 * Список маршрутов и увведомление
 */
export interface ITransportDto {
	/**
	 * Признак что пользователь может добавлять уведомление
	 */
	canAddNotification?: boolean;
	/**
	 * Список маршрутов
	 */
	transportList?: IRouteDto[] | null;
	transportNotify?: ITransportNotifyDto;
}
