/**
 * Company API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IWidgetType } from './widget-type';

/**
 * Описание настройки виджета
 */
export interface IWidgetDto {
	type?: IWidgetType;
	/**
	 * Включен или выключен виджет
	 */
	enabled?: boolean;
}
export namespace IWidgetDto {}
