/**
 * Company API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Тип виджета  1 = Banners  2 = AuctionSales  3 = ThanksPartner  4 = Wins  5 = BirthDays
 */
export type IWidgetType = 1 | 2 | 3 | 4 | 5;

export const IWidgetType = {
    NUMBER_1: 1 as IWidgetType,
    NUMBER_2: 2 as IWidgetType,
    NUMBER_3: 3 as IWidgetType,
    NUMBER_4: 4 as IWidgetType,
    NUMBER_5: 5 as IWidgetType
};

